- name: configure the backend
  hosts: backend
  become: yes
  tasks:

  - name: disable curret nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: installed

  - name: create a user expense
    ansible.builtin.user:
      name: expense

  - name: create a app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the application code to created app directory
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip the application code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: install the nodejs dependencies
    community.general.npm:
      path: /app
