- name: configure the backend
  hosts: backend
  become: yes
  tasks:

  - name: disable curret nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: installed

  - name: create a user expense
    ansible.builtin.user:
      name: expense

  - name: create a app directory
    ansible.builtin.file:
      path: app
      state: directory