- name: configure frontend
  hosts: frontend
  become: yes
  tasks:

  - name: install the nginx server
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: start and enable the nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete the directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create a directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory