- name: configure frontend
  hosts: frontend
  become: yes
  tasks:

  - name: install the nginx server
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: start and enable the nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete the directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create a directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download the frontend content
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

    - name: unzip the application code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: copy backend service file from anisble server to remote backend server
      ansible.builtin.copy:
        src: frontend.conf
        dest: /etc/nginx/default.d/expense.conf  

    - name: restart the nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted