- name: Configure mysql server
  hosts: mysql
  become: yes
  tasks:

  - name: Install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enabke the mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes